logoText = "å…è²»é–‹æºTRPGä¸­æ–‡åŒ–åœ˜éšŠ"
logoType = "short" # long, short
description = "æ‚¨æœ€å®‰å¿ƒä¿¡è³´çš„ä¸­æ–‡åŒ–TRPGè¦å‰‡ç¶²ç«™"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = "images/whoami/avatar.png"
themecolor = "light"

themeOptions = ["light", "hacker", "solarized", "kimbie"]

notAllowedTypesInHome = ["about", "archive"]
notAllowedTypesInHomeSidebar = ["about", "archive"]
notAllowedTypesInArchive = ["about", "archive"]
notAllowedTypesInHomeFeed = ["about", "archive"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = false
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags"]

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = false
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 20
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â˜•"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
pinIcon = "ğŸ“Œ"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"

# whoami
myname = ""
email = "freeandopentrpg@gmail.com"
whoami = "è¯çµ¡æˆ‘å€‘"
bioImageUrl = "images/whoami/avatar.png"
useGravatar = false
location = ""
organization = ""
link = ""

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = false
enableSidebarCategories = false
enableHomeSidebarTitles = false
enableListSidebarTitles = false
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 10
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = false
enableLangChange = false
enableThemeChange = false

# service
googleTagManager = "GTM-KNBXC8B" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false



[socialOptions]
  email = "mailto:freeandopentrpg@gmail.com"
  twitter = "https://twitter.com/Mc32emizCKNUZ6l"
  plurks = "https://www.plurk.com/freeandopentrpg"
  discord = "https://discord.gg/FDgGuCH"

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
[[share]]
  name = "facebook"
  username = ""
[[share]]
  name = "twitter"

[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""